import datetime
import hashlib
import os
import random
import re
from datetime import timedelta
import grequests
import requests
from bs4 import BeautifulSoup
from moviepy.editor import concatenate_videoclips, VideoFileClip
from natsort import natsorted
from settings import domains, user_agents
from functions import print_main_menu,print_vod_type_menu,print_vod_recovery_menu,print_clip_type_menu,print_clip_recovery_menu,print_clip_format_menu,get_default_directory,generate_log_filename,generate_vod_filename,generate_website_links,return_header,remove_file,format_timestamp,get_vod_age,is_vod_muted,get_duration,get_reps,get_clip_format,get_all_clip_urls,return_username,return_vod_id,remove_chars_from_ordinal_numbers,return_file_contents,get_vod_urls,parse_duration_streamscharts,parse_duration_twitchtracker,parse_duration_sullygnome,parse_datetime_streamscharts,parse_datetime_twitchtracker,parse_datetime_sullygnome,unmute_vod,dump_playlist,return_valid_file,get_all_playlist_segments,get_valid_segments,return_segment_ratio,vod_recover,manual_vod_recover,website_vod_recover,website_clip_recover,bulk_vod_recovery,clip_recover,manual_clip_recover,parse_clip_csv_file,parse_vod_csv_file,get_random_clips,bulk_clip_recovery,download_m3u8,download_clips,run_script

user_agents = user_agents
domains = domains

run_script()